/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  images: {
    unoptimized: true, // Required because server-side image optimization doesn't work with static export
  },
  basePath: '/<REPO_NAME>', // Required if not deploying to a custom domain
  assetPrefix: '/<REPO_NAME>',
};

module.exports = nextConfig;
"scripts": {
  "build": "next build && next export"
}
